### ISSUE TITLE
The latest version is not updated on Packagist

### ISSUE THREAD

**Issue by ElfSundae** [laravel-notification-channels/bearychat#12]
cc @themsaid @freekmurze
I bumped up a new version 1.2.1 two days ago, it seems the webhook has broken, the latest version is not updated on [Packagist](https://packagist.org/packages/laravel-notification-channels/bearychat). Please update it for me, thank you.

https://github.com/laravel-notification-channels/apn/issues/62

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄

**Comment by ElfSundae** [comment]
@atymic Thanks a lot for your great work 👍

**Comment by ElfSundae** [comment]
@atymic Thanks a lot for your great work 👍
