### ISSUE TITLE
BearyChat is Dead, this package shall be archived.

### ISSUE THREAD

**Issue by xiaohuilam** [laravel-notification-channels/bearychat#15]

**Comment by ElfSundae** [comment]
Just noticed https://bearychat.com shows server error, is there any official death announcement?

**Comment by xiaohuilam** [comment]
> Just noticed https://bearychat.com shows server error, is there any official death announcement?


Seems no official announcement, but got some news from ex-employee:

bearychat和pubu.im这种类slack服务是不是在国内已死了？ - Loddit的回答 - 知乎
https://www.zhihu.com/question/50419854/answer/121601576

See author's latest comment.

> 2018 年团队被滴滴收购了，战略方向调整，收紧了 SaaS 服务的资源，更大精力投入内部工具了，而今年7月开始无访问的直接原因和给客户的解决方案还不得而知，应该是下线产品了。

> In 2018, the team was acquired by DidiTaxi Group, the strategic direction was adjusted, the resources of SaaS services were tightened, and more energy was devoted to internal tools. However, the direct reason for the lack of access since July this year and the solutions for customers are still unknown, It should be turned offline.

**Comment by ElfSundae** [comment]
@xiaohuilam Thank you for the reminder, let's wait a few months then.
